apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicd-devops
  template:
    metadata:
      labels:
        app: cicd-devops
    spec:
      containers:
        - name: cicd-devops
          image: cicd-devops
          ports:
            - containerPort: 3000
