apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: cicd-devops

images:
- name: cicd-devops
  newName: acambinza/ci-cd-devops
  newTag: 778e255573e7820212b29050b19ff686d85e7aba
