apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: cicd-devops

images:
- name: cicd-devops
  newName: acambinza/cicd-devops
  newTag: 28b4c6d84ed979a59216b994c1357bb4a000fe1a
