apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cicd-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicd-pod-devops
  template:
    metadata:
      labels:
        app: cicd-pod-devops
    spec:
      containers:
        - name: container-cicd-replicaset
          image: acambinza/ci-cd-devops:dd8f90733022c97f4dbb9eb2b378a5d360a0e911
          ports:
            - containerPort: 3000
